### ISSUE TITLE
Consider switching to JsonSchema draft-2020-12

### ISSUE THREAD

**Issue by yeldiRium** [thenativeweb/validate-value#393]
`ajv` supports JsonSchema draft-2020-12, but [since it is breaking it is not used by default](https://ajv.js.org/json-schema.html#draft-2020-12).

Since the new draft brings some cool things with it, we should consider switching to it. This will be a breaking change for the library, since draft-2020-12 is not fully backwards compatible. But I have yet to find actually incompatible things. I don't think many of our projects will have a problem with this upgrade.

**Comment by goloroden** [comment]
I think, even if there are incompatibilities, it's reasonable to move forward (I assume that the new version will be the base for future development). So … of course it's good to double-check where it may break, but as said, if it's the foundation, we should do it anyway.
