### ISSUE TITLE
Misleading error message when multiple parsing errors would have been thrown

### ISSUE THREAD

**Issue by matthiashermsen** [thenativeweb/validate-value#436]
Given the following sample code ( https://codesandbox.io/s/distracted-greider-7z7m23?file=/src/index.ts )

```ts
import { JsonSchema, getDefaultAjvInstance, Parser } from "validate-value";

const typeSchema = (type: "boolean" | "number"): JsonSchema => ({
  type: "string",
  enum: [type]
});

const booleanModelConfigurationSchema = (): JsonSchema => ({
  type: "object",
  properties: {
    type: typeSchema("boolean")
  },
  required: ["type"],
  additionalProperties: false
});

const numberModelConfigurationSchema = (): JsonSchema => ({
  type: "object",
  properties: {
    type: typeSchema("number"),
    additionalFieldForNumbersOnly: { type: "boolean" }
  },
  required: ["type", "additionalFieldForNumbersOnly"],
  additionalProperties: false
});

const ajvInstance = getDefaultAjvInstance();

const parser = new Parser(
  {
    type: "object",
    oneOf: [booleanModelConfigurationSchema(), numberModelConfigurationSchema()]
  },
  { ajvInstance }
);

const result = parser.parse({ type: "number" });

result.unwrapOrThrow();
```

I would expect it to throw the error

> Missing required property: additionalFieldForNumbersOnly (at value.additionalFieldForNumbersOnly).

but instead it throws

> No enum match (number), expects: boolean (at value.type).

which is confusing. When reproducing the behaviour with plain ajv ( https://codesandbox.io/s/agitated-sunset-e7hzwv?file=/src/index.ts )

```ts
import Ajv from "ajv";

const ajvInstance = new Ajv();

const typeSchema = (type: "boolean" | "number") => ({
  type: "string",
  enum: [type]
});

const booleanModelConfigurationSchema = {
  type: "object",
  properties: {
    type: typeSchema("boolean")
  },
  required: ["type"],
  additionalProperties: false
};

const numberModelConfigurationSchema = {
  type: "object",
  properties: {
    type: typeSchema("number"),
    additionalFieldForNumbersOnly: { type: "boolean" }
  },
  required: ["type", "additionalFieldForNumbersOnly"],
  additionalProperties: false
};

const validate = ajvInstance.compile({
  type: "object",
  oneOf: [booleanModelConfigurationSchema, numberModelConfigurationSchema]
});

const isValid = validate({ type: "number" });

if (isValid) {
  console.info("everything is fine");
} else {
  validate.errors?.forEach((error) => console.error(error.message));
}
```

you will see that 3 errors have been thrown

> must be equal to one of the allowed values

> must have required property 'additionalFieldForNumbersOnly'

> must match exactly one schema in oneOf

I'm assuming the validate-value error represents the second error from ajv. Unfortunately the validate-value error is misleading because I would expect a parsing error based on the `numberModelConfigurationSchema` ( missing field ) instead of telling me to use the `booleanModelConfigurationSchema`.

I don't think that this issue is a bug but it's quite hard to write tests for it because you won't be able to make assertions for missing fields.

Do you have any suggestions?

**Comment by goloroden** [comment]
Hmmm 🤔 

It's actually is a good question how to deal with it in a reasonable way.

One thing we intentionally dropped was the option to have multiple errors, but the downside of this is that if the message we select is not the most specific one it can lead to clumsy behavior.

TBH I don't have a good idea on how to handle this case, as no matter what we do in a generic way to improve this situation may lead to a worse solution in a different situation.

The best bet would probably be to add specific handling for exactly this case, but it's hard to detect generically.

So, in the end, I think that you will have to live with this error message.

**Comment by matthiashermsen** [comment]
Thanks for your reply :)
I think the behaviour is fine for now. It's important that any error will be thrown ...

I don't have any ideas to solve this problem, closing this for now
