### ISSUE TITLE
Valid JsonSchema ( draft-2020-12 ) is invalid with validate-value v10.0.0

### ISSUE THREAD

**Issue by matthiashermsen** [thenativeweb/validate-value#441]
The following example works fine for v9.4.0

```js
const { Parser } = require("validate-value");

const equalSchema = {
  $id: "equal",
  type: "object",
  properties: {
    $eq: {
      type: "array",
      items: [
        { type: "string" },
        { anyOf: [ { type: "string" }, { type: "number" }, { type: "boolean" } ], },
      ],
      minItems: 2,
      maxItems: 2,
    },
  },
  required: ["$eq"],
  additionalProperties: false,
};

new Parser(equalSchema);
```

When migrating to v10.0.0 ( https://github.com/thenativeweb/validate-value/pull/437 ) I get the error message

> Error: schema is invalid: data/properties/$eq/items must be object,boolean

but AFAIK the schema should be ok. The schema works with Ajv v8.11.2 ( latest )

```js
const Ajv = require("ajv");

const ajvInstance = new Ajv();

const equalSchema = {
  $id: "equal",
  type: "object",
  properties: {
    $eq: {
      type: "array",
      items: [
        { type: "string" },
        { anyOf: [ { type: "string" }, { type: "number" }, { type: "boolean" } ], },
      ],
      minItems: 2,
      maxItems: 2,
    },
  },
  required: ["$eq"],
  additionalProperties: false,
};

const validate = ajvInstance.compile(equalSchema);

const data = { $eq: [ "isTrue", false ] };

const isValid = validate(data);

if (!isValid) {
  validate.errors?.forEach((error) => console.log(error.message));
}
```

I don't think this is related to validate-value because the constructor of `Parser` passes the schema to the plain Ajv instance => https://github.com/thenativeweb/validate-value/blob/main/lib/Parser.ts#L22

And validate-value is using the latest Ajv version => https://github.com/thenativeweb/validate-value/blob/main/package.json#L32

Do you have any ideas what might be wrong?

**Comment by yeldiRium** [comment]
As we have discussed earlier in person, this is due to a breaking change in the current schema version (2020-12).

The reason for the different result when using `ajv` directly is that we explicitly use version `2020`, while `ajv` by default uses an older version, which is what you are using in the second code example with `require('ajv')`.

The breaking change is that the semantics of `items` and `prefixItems` have changed, see https://ajv.js.org/json-schema.html#items-in-draft-2020-12.

So in your schema you have to replace the `items` on line 9 with `prefixItems` to achieve your goal.

**Comment by matthiashermsen** [comment]
@yeldiRium replacing `items` with `prefixItems` fixes the error :) But unfortunately I didn't check the code against a TS project, I'm sorry.

The schema must be of type `JsonSchema` but `prefixItems` does not exist in type `JSONSchema7`.

```ts
import { Parser, JsonSchema } from "validate-value";

const equalSchema: JsonSchema = {
  $id: "equal",
  type: "object",
  properties: {
    $eq: {
      type: "array",
      /*

error TS2322: Type '{ type: "array"; prefixItems: ({ type: string; } | { anyOf: { type: string; }[]; })[]; minItems: number; maxItems: number; }' is not assignable to type 'JSONSchema7Definition'.
  Object literal may only specify known properties, and 'prefixItems' does not exist in type 'JSONSchema7'.

      */
      prefixItems: [
        { type: "string" },
        { anyOf: [ { type: "string" }, { type: "number" }, { type: "boolean" } ], },
      ],
      minItems: 2,
      maxItems: 2,
    },
  },
  required: ["$eq"],
  additionalProperties: false,
};

new Parser(equalSchema);
```

@goloroden would you mind opening this ticket again?

**Comment by goloroden** [comment]
As @matthiashermsen and I figured out, AJV already supports this, including the "parse don't validate" approach (https://ajv.js.org/guide/typescript.html#utility-types-for-schemas).

So, the question is whether you might want to use AJV directly, and maybe use only the code for creating the error messages.

Hence, I'm going to close this (again 😉).
